### ISSUE TITLE
--export needs a graphical environment to work

### ISSUE THREAD

**Issue by fgaz** [agateau/sfxr-qt#11]
I noticed that `--export` needs a graphical environment to work even though no window is created. This is a problem when running it in headless environment, such as CI.

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by Huitsi** [comment]
I don't know how easy or difficult this is to fix for a Qt application. In any case it might be worthwhile to make a separate minimal CLI application for exporting. I think the first step towards this would be to split the back end into it's own repo (libsfxr?).

**Comment by agateau** [comment]
A separate CLI application would work, but I think it is not necessary: it should be enough to create a QCoreApplication instead of a QGuiApplication if the `--export` argument is present. The only difficulty I know of is that QCommandLineParser expects the Qt application instance (either QCoreApplication or QGuiApplication) to already exist, so the code would have to look for `--export` by iterating on `argv` manually, and only then create either a QGuiApplication or a QCoreApplication.

Would you be interested in looking into it @Huitsi?

**Comment by Huitsi** [comment]
Sure, I'll look into it. There does seem to be a few ways to do it – for instance, it seems QCommandLineParser doesn't necessarily need any Q*Application.

If the CLI export feature really takes off the separate CLI application might still become worth the effort though.

**Comment by agateau-gg** [comment]
> Sure, I'll look into it. There does seem to be a few ways to do it – for instance, it seems QCommandLineParser doesn't necessarily need any Q*Application.

If I am not mistaken, it's not directly visible, but features like translated strings in the help messages do require a QCoreApplication.

> If the CLI export feature really takes off the separate CLI application might still become worth the effort though.

That's possible indeed, but I'd rather keep it self-contained for now.
